config/routes.rb
Rails.application.routes.draw do
  
  
  get '/login',to:'access#new'
  post '/login', to:'access#create'
  delete '/logout',to:'access#destroy', as:'logout'
  get '/admin',to:'admin#index'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  get '/shopper',to:'shopper#index'
  resources :products
  root "shopper#index", as: 'root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Store</title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<div id="banner">
<%= @page_title || "Our Products" %>
</div>
<div id="columns">
<div id="side">
<div id="cart">
	<% if !@cart.nil? %>
		<%= render @cart %>
	<% end %>
</div>
<ul>
<li><a href="http://localhost:3000">Home</a></li>
<li><a href="http://localhost:3000">Questions</a></li>
<li><a href="http://localhost:3000">News</a></li>
<li><a href="http://localhost:3000">Contact</a></li>
</ul>

<% if session[:user_id] %>
<ul>
<li><%= link_to 'Orders', orders_path %></li>
<li><%= link_to 'Products', products_path %></li>
<li><%= link_to 'Users', users_path %></li>
</ul>
<%= button_to 'Logout', logout_path, method: :delete %>
<% end %>
</div>
<div id="main">
<%= yield %>
</div>
</div>
</body>
</html>